#!/usr/bin/env python3
"""Build the community companion gallery from introductions and WebP photos."""

from __future__ import annotations

import argparse
from pathlib import Path


SKIP_NAMES = {"README.md", "GALLERY.md", "_template.md"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--community-dir", type=Path, default=Path("community-pets"))
    parser.add_argument("--output", type=Path, default=Path("community-pets/GALLERY.md"))
    args = parser.parse_args()

    rows: list[tuple[str, str]] = []
    for intro_path in sorted(args.community_dir.glob("*.md")):
        if intro_path.name in SKIP_NAMES:
            continue
        lines = [line.strip() for line in intro_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        if len(lines) != 1:
            raise SystemExit(f"{intro_path}: expected exactly one non-empty line")
        photo_path = args.community_dir / "photos" / f"{intro_path.stem}.webp"
        photo = f'<img src="photos/{photo_path.name}" alt="{intro_path.stem}" width="180">' if photo_path.exists() else "—"
        rows.append((lines[0], photo))

    content = [
        "# Community companion gallery",
        "",
        "This file is generated by `scripts/generate-community-gallery.py`.",
        "",
        "| Companion | Photo |",
        "| --- | --- |",
    ]
    content.extend(f"| {intro} | {photo} |" for intro, photo in rows)
    content.append("")
    args.output.write_text("\n".join(content), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
